### ISSUE TITLE
Problems with bct library

### ISSUE THREAD

**Issue by ElsaPMC** [netneurolab/conn2res#41]
`from bct import get_components, distance_bin, reference`

Hi everyone, thankyou so much for this available tool, I have a problem with the bct library to import get_components, distance_bin, reference, how can I fix it, because apparently bct is not found as a file in the repository, so I looked for it in pypi and I understand that it is the brain connectivity toolboox for python and it appears as bctpy because bct is a version for matlab, then I want to know if the errors to import everything are because they are called disitnto in this case and then get_components, distance_bin, reference would change.  I hope you can help me and thank you in advance.

**Comment by bachnguyenTE** [comment]
Once you've installed `bctpy` from the requirements of the repository, the import statement using `bct` you saw in the code should work fine and should not change the behavior of any of the functions you listed. Make sure that you follow the instructions for installing the requirements for conn2res correctly, it's best that you can do so with a blank new conda environment to avoid conflicts. Let me know if your issue is resolved!

**Comment by ElsaPMC** [comment]
it works!, thankyou @bachnguyenTE
