### ISSUE TITLE
Guidance on Using Custom Dataset and Connectivity Matrix with conn2res

### ISSUE THREAD

**Issue by yajairazepeda** [netneurolab/conn2res#43]
Hello,

I am currently working with the conn2res tool and I have some questions regarding its usage.

Firstly, I noticed that the tasks used in the dataset are cognitive tasks extracted from another tool called NeuroGym. I am interested in using my own dataset instead. Could you provide some guidance on the nature of the dataset that conn2res expects? Specifically, what format should my dataset be in, and what changes would I need to make in the code to ensure it works with my custom dataset?

Secondly, I understand that conn2res uses a connectivity matrix from an existing database. However, I would like to use my own connectivity matrix. Could you provide some instructions or guidelines on how to incorporate my own connectivity matrix into the conn2res workflow?

Lastly, I am having some difficulty understanding the structure of the codebase. Could you clarify which is the main code file? Is it the one labeled as 'tutorial' or is it one of the files in the 'examples' directory?

Any help or guidance would be greatly appreciated. Thank you in advance for your time and assistance.

**Comment by bachnguyenTE** [comment]
For the dataset, currently, the repository supports sequential numerical data as inputs. If you want to use image datasets such as MNIST, one way to make your data compatible is to flatten the image so that you are left with a sequential representation of it. Additionally, you can provide the embeddings of another data format that has been preprocessed by another model (e.g., text embeddings from LLMs, or image embedding from CNNs) as numerical vectorized input to the reservoir. You can change the code in `reservoir.py` to either make sure that the input layer to the reservoir is compatible with the reservoir itself or make changes to the entire model input pipeline.

For adjacency, the provided code will directly load in a square (weighted) adjacency matrix from a `.npy` file that you provided. For the current version of the code, you have to ensure that the edges of the networks are either zeroes (representing the absence of connection) or a positive value denoting the connection strength between two nodes. If you want to include inhibitory connections or negative edges, you can try modifying the `scale` function in `connectivity.py` to ensure that it only normalizes non-zero edges. For an example of how to initialize the reservoir with an adjacency matrix, refer to the `tutorial` notebook and file in folder `examples`.

There is no "main code file" since the repository is a library you can use in your code running reservoir models. However, as you've mentioned, the files inside the `examples` folders are code that you can run to see the repository in action.

Let me know if you are unclear about anything, or if there is something else you would like to know. Thank you!
